SERVER_PORT: 8080
SESSION_SIGNATURE: session

POSTGRES_USER: user
POSTGRES_PASSWORD: password
POSTGRES_DB: gramm
POSTGRES_PORT: 5432
POSTGRES_HOST: db
MIGRATIONS_PATH: file://db/migrations

SESSION_TOKEN_LIFESPAN: 90d

AUTH_REDIS_HOST: auth_redis
AUTH_REDIS_PORT: 6380
AUTH_REDIS_PASSWORD: password
AUTH_REDIS_DB: 0

CSRF_SECRET: csrf_secret
CSRF_TIMEOUT: 1h

MINIO_HOST: minio
MINIO_PUBLIC_HOST: localhost
MINIO_PORT: 9000
MINIO_COMMAND_PORT: 9001
MINIO_ACCESS_KEY: minioadmin
MINIO_SECRET_KEY: minioadmin123
MINIO_BUCKET_NAME: attachments
MINIO_USE_SSL: true

AUTH_GRPC_PORT: 50051
AUTH_SERVICE_ADDR: auth-service:50051

USER_GRPC_PORT: 50052
USER_SERVICE_ADDR: user-service:50052

CHATS_GRPC_PORT: 50053
CHATS_SERVICE_ADDR: chats-service:50053

ENVIRONMENT: development

ELASTICSEARCH_PORT: 9200
ELASTICSEARCH_URL: https://elasticsearch:9200
ELASTICSEARCH_CONTACTS_INDEX: contacts
ELASTICSEARCH_ADMIN_PASSWORD: admin
ELASTICSEARCH_USERNAME: admin
ELASTICSEARCH_PASSWORD: admin

METRICS_PORT: 2112
APP_METRICS_PORT: 2112

AUTH_METRICS_PORT: 9101
USER_METRICS_PORT: 9102
CHATS_METRICS_PORT: 9103
PROMETHEUS_PORT: 9090
GRAFANA_PORT: 3000

NODE_EXPORTER_PORT: 9100

GRAFANA_ADMIN_USER: admin
GRAFANA_ADMIN_PASSWORD: admin