SERVER_PORT: 8080
SESSION_SIGNATURE: session
POSTGRES_USER: user
POSTGRES_PASSWORD: password
POSTGRES_DB: gramm
POSTGRES_PORT: 5432
POSTGRES_HOST: db
MIGRATIONS_PATH: file://db/migrations
SESSION_TOKEN_LIFESPAN: 90d
AUTH_REDIS_HOST: auth_redis
AUTH_REDIS_PORT: 6380
AUTH_REDIS_PASSWORD: password
AUTH_REDIS_DB: 0