SERVER_PORT=8080
SESSION_SIGNATURE=session

POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
POSTGRES_DB=messenger_db
POSTGRES_PORT=5432
POSTGRES_HOST=localhost
POSTGRES_SSLMODE=disable

SESSION_TOKEN_LIFESPAN=90d

AUTH_REDIS_HOST=localhost
AUTH_REDIS_PORT=6379
AUTH_REDIS_PASSWORD=password
AUTH_REDIS_DB=0

CSRF_SECRET=csrf_secret_local_dev

MIGRATIONS_PATH=file://db/migrations

MINIO_HOST=localhost
MINIO_PUBLIC_HOST=localhost
MINIO_PORT=9000
MINIO_COMMAND_PORT=9001
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin123
MINIO_BUCKET_NAME=avatars
MINIO_USE_SSL=false