SERVER_PORT: 8080
SESSION_SIGNATURE: session

POSTGRES_USER: user
POSTGRES_PASSWORD: password
POSTGRES_DB: gramm
POSTGRES_PORT: 5432
POSTGRES_HOST: db
MIGRATIONS_PATH: file://db/migrations

SESSION_TOKEN_LIFESPAN: 90d

AUTH_REDIS_HOST: auth_redis
AUTH_REDIS_PORT: 6380
AUTH_REDIS_PASSWORD: password
AUTH_REDIS_DB: 0

CSRF_SECRET: csrf_secret
CSRF_TIMEOUT: 1h

MINIO_HOST: minio
MINIO_PUBLIC_HOST: localhost
MINIO_PORT: 9000
MINIO_COMMAND_PORT: 9001
MINIO_ACCESS_KEY: minioadmin
MINIO_SECRET_KEY: minioadmin123
MINIO_BUCKET_NAME: avatars
MINIO_USE_SSL: false

AUTH_GRPC_PORT: 50051
AUTH_SERVICE_ADDR: localhost:50051

USER_GRPC_PORT: 50052
USER_SERVICE_ADDR: localhost:50052