services:
  app:
    build: .
    container_name: gramm_app
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      db:
        condition: service_healthy
      auth_redis:
        condition: service_healthy
    networks:
      - gramm-network
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      SESSION_SIGNATURE: ${SESSION_SIGNATURE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
      POSTGRES_SSLMODE: disable
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
      SESSION_TOKEN_LIFESPAN: ${SESSION_TOKEN_LIFESPAN}
      AUTH_REDIS_HOST: auth_redis
      AUTH_REDIS_PORT: ${AUTH_REDIS_PORT}
      AUTH_REDIS_PASSWORD: ${AUTH_REDIS_PASSWORD}
      AUTH_REDIS_DB: ${AUTH_REDIS_DB}
      CSRF_SECRET: ${CSRF_SECRET}
      MINIO_HOST: minio
      MINIO_PUBLIC_HOST: ${MINIO_PUBLIC_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
    command: sh -c "./migrate && ./main"

  db:
    image: postgres:15
    container_name: gramm_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gramm-network
  
  auth_redis:
    image: redis:alpine
    container_name: gramm_redis
    command: redis-server --bind 0.0.0.0 --port 6379 ${AUTH_REDIS_PASSWORD:+--requirepass} ${AUTH_REDIS_PASSWORD}
    ports:
      - "${AUTH_REDIS_PORT}:6379"
    volumes:
      - auth_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gramm-network
  
  minio:
    image: minio/minio:latest
    container_name: gramm_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - gramm-network

networks:
  gramm-network:
    driver: bridge

volumes:
  postgres_data:
  auth_redis_data:
  minio_data: