services:
  app:
    build: .
    container_name: gramm_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gramm-network
    environment:
      SERVER_PORT: 8080
      JWT_SIGNATURE: my_secret_key
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gramm
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      MIGRATIONS_PATH: file://db/migrations
      JWT_TOKEN_LIFESPAN: 24h
      MINIO_HOST: minio
      MINIO_PUBLIC_HOST: localhost
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET_NAME: avatars
      MINIO_USE_SSL: false
    command: sh -c "./migrate && ./main"

  db:
    image: postgres:15
    container_name: gramm_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gramm
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gramm"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gramm-network
  
  auth_redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0 --port 6380 --requirepass password
    ports:
      - "6380:6380"
    volumes:
      - auth_redis_data:/data
    environment:
      REDIS_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -p 6380 -a password ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gramm-network
  
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - gramm-network

networks:
  gramm-network:
    driver: bridge

volumes:
  postgres_data:
  auth_redis_data:
  minio_data: