name: CD
on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_LOGIN: "lzimin05"
  IMAGE_NAME: "100gramm_backend_app"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v5
      - name: Установка qemu
        uses: docker/setup-qemu-action@v3
      - name: Установка docker build
        uses: docker/setup-buildx-action@v3
      - name: Аутентификация в docker hub
        uses: docker/login-action@v2
        with: 
          username: ${{ env.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Сборка и отправка образа в DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}
          file: ./Dockerfile
          build-args: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            REGISTRY=${{ env.DOCKER_HUB_LOGIN }}
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: copy docker compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VM_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/app"
      - name: deploy
        uses: appleboy/ssh-action@v1.2.2
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VM_KEY }}
          envs: DOCKER_HUB_LOGIN, IMAGE_NAME
          script: |
            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u $DOCKER_HUB_LOGIN --password-stdin
            docker compose down
            docker system prune -af
            docker pull $DOCKER_HUB_LOGIN/$IMAGE_NAME:latest
            cd app && docker compose up -d
        